"""raw_questions_audit_columns

Revision ID: c5430586d6e3
Revises: 7c51c3f6fcd7
Create Date: 2026-04-22 21:08:19.433049

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c5430586d6e3'
down_revision: Union[str, Sequence[str], None] = '7c51c3f6fcd7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 已有行时 NOT NULL 无默认值会失败；先 server_default 再摘掉默认，由应用层写入
    op.add_column(
        "raw_questions",
        sa.Column("created_by", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
    )
    op.add_column(
        "raw_questions",
        sa.Column("updated_by", sa.BigInteger(), nullable=False, server_default=sa.text("0")),
    )
    op.alter_column("raw_questions", "created_by", server_default=None)
    op.alter_column("raw_questions", "updated_by", server_default=None)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('raw_questions', 'updated_by')
    op.drop_column('raw_questions', 'created_by')
    # ### end Alembic commands ###
